#! /usr/bin/env bash
rm -rf ~/.ackrc
rm -rf ~/.bash_profile
rm -rf ~/.bashrc
rm -rf ~/.cache
rm -rf ~/.conda
rm -rf ~/.config
rm -rf ~/.ctags
rm -rf ~/.gitconfig
rm -rf ~/.gitignore_global
rm -rf ~/.ideavimrc
rm -rf ~/.inputrc
rm -rf ~/.undodir
rm -rf ~/.vim
rm -rf ~/.vim_backups
rm -rf ~/.viminfo
rm -rf ~/.vimrc
rm -rf ~/envs
rm -rf ~/miniconda
rm -rf ~/rcconda.sh
