# Run this to create: conda env create --force -f environment_arm.yml
# To update with any changes:  conda env update -f environment_arm.yml
name: viz
channels:
    - conda-forge
dependencies:
    - python=3.9
    - astropy
    - cvxpy
    - jupyterlab
    - numpy
    - pip
    - psycopg2
    - scikit-learn
    - scipy
    - statsmodels

    - pip:
        - altair
        - attrs
        - click
        - cookiecutter
        - daiquiri
        - dataset
        - duckdb
        - easier
        - flake8
        - fleming
        - fuzzypicker
        - gspread
        - holoviews[recommended]
        - hvplot
        - jinjasql
        - lifelines
        - networkx
        - nose
        - oauth2client
        - pandashells[full]
        - patsy
        - pdbpp
        - psutil
        - pytest
        - python-dateutil
        - requests
        - seaborn
        - simple-salesforce
        - snakemake
        - streamz
        - tdigest
        - tqdm
        - hvplot
        - visidata
        - wrapt
