#! /usr/bin/env bash
(cd /packages && ctags -R --fields=+l --languages=python --python-kinds=-iv -f ./tags . $(/Users/rob/anaconda/bin/python -c "import os, sys; print(' '.join('{}'.format(d) for d in sys.path if os.path.isdir(d)))"))
